// Surah metadata for all 114 Surahs of the Quran

export interface SurahInfo {
    number: number;
    arabicName: string;
    englishName: string;
    englishTranslation: string;
    versesCount: number;
    revelationType: 'Makki' | 'Madani';
}

export const surahList: SurahInfo[] = [
    { number: 1, arabicName: 'الفاتحة', englishName: 'Al-Fatiha', englishTranslation: 'The Opening', versesCount: 7, revelationType: 'Makki' },
    { number: 2, arabicName: 'البقرة', englishName: 'Al-Baqara', englishTranslation: 'The Cow', versesCount: 286, revelationType: 'Madani' },
    { number: 3, arabicName: 'آل عمران', englishName: 'Ali \'Imran', englishTranslation: 'Family of Imran', versesCount: 200, revelationType: 'Madani' },
    { number: 4, arabicName: 'النساء', englishName: 'An-Nisa', englishTranslation: 'The Women', versesCount: 176, revelationType: 'Madani' },
    { number: 5, arabicName: 'المائدة', englishName: 'Al-Ma\'ida', englishTranslation: 'The Table Spread', versesCount: 120, revelationType: 'Madani' },
    { number: 6, arabicName: 'الأنعام', englishName: 'Al-An\'am', englishTranslation: 'The Cattle', versesCount: 165, revelationType: 'Makki' },
    { number: 7, arabicName: 'الأعراف', englishName: 'Al-A\'raf', englishTranslation: 'The Heights', versesCount: 206, revelationType: 'Makki' },
    { number: 8, arabicName: 'الأنفال', englishName: 'Al-Anfal', englishTranslation: 'The Spoils of War', versesCount: 75, revelationType: 'Madani' },
    { number: 9, arabicName: 'التوبة', englishName: 'At-Tawba', englishTranslation: 'The Repentance', versesCount: 129, revelationType: 'Madani' },
    { number: 10, arabicName: 'يونس', englishName: 'Yunus', englishTranslation: 'Jonah', versesCount: 109, revelationType: 'Makki' },
    { number: 11, arabicName: 'هود', englishName: 'Hud', englishTranslation: 'Hud', versesCount: 123, revelationType: 'Makki' },
    { number: 12, arabicName: 'يوسف', englishName: 'Yusuf', englishTranslation: 'Joseph', versesCount: 111, revelationType: 'Makki' },
    { number: 13, arabicName: 'الرعد', englishName: 'Ar-Ra\'d', englishTranslation: 'The Thunder', versesCount: 43, revelationType: 'Madani' },
    { number: 14, arabicName: 'إبراهيم', englishName: 'Ibrahim', englishTranslation: 'Abraham', versesCount: 52, revelationType: 'Makki' },
    { number: 15, arabicName: 'الحجر', englishName: 'Al-Hijr', englishTranslation: 'The Rocky Tract', versesCount: 99, revelationType: 'Makki' },
    { number: 16, arabicName: 'النحل', englishName: 'An-Nahl', englishTranslation: 'The Bee', versesCount: 128, revelationType: 'Makki' },
    { number: 17, arabicName: 'الإسراء', englishName: 'Al-Isra', englishTranslation: 'The Night Journey', versesCount: 111, revelationType: 'Makki' },
    { number: 18, arabicName: 'الكهف', englishName: 'Al-Kahf', englishTranslation: 'The Cave', versesCount: 110, revelationType: 'Makki' },
    { number: 19, arabicName: 'مريم', englishName: 'Maryam', englishTranslation: 'Mary', versesCount: 98, revelationType: 'Makki' },
    { number: 20, arabicName: 'طه', englishName: 'Ta-Ha', englishTranslation: 'Ta-Ha', versesCount: 135, revelationType: 'Makki' },
    { number: 21, arabicName: 'الأنبياء', englishName: 'Al-Anbiya', englishTranslation: 'The Prophets', versesCount: 112, revelationType: 'Makki' },
    { number: 22, arabicName: 'الحج', englishName: 'Al-Hajj', englishTranslation: 'The Pilgrimage', versesCount: 78, revelationType: 'Madani' },
    { number: 23, arabicName: 'المؤمنون', englishName: 'Al-Mu\'minun', englishTranslation: 'The Believers', versesCount: 118, revelationType: 'Makki' },
    { number: 24, arabicName: 'النور', englishName: 'An-Nur', englishTranslation: 'The Light', versesCount: 64, revelationType: 'Madani' },
    { number: 25, arabicName: 'الفرقان', englishName: 'Al-Furqan', englishTranslation: 'The Criterion', versesCount: 77, revelationType: 'Makki' },
    { number: 26, arabicName: 'الشعراء', englishName: 'Ash-Shu\'ara', englishTranslation: 'The Poets', versesCount: 227, revelationType: 'Makki' },
    { number: 27, arabicName: 'النمل', englishName: 'An-Naml', englishTranslation: 'The Ant', versesCount: 93, revelationType: 'Makki' },
    { number: 28, arabicName: 'القصص', englishName: 'Al-Qasas', englishTranslation: 'The Stories', versesCount: 88, revelationType: 'Makki' },
    { number: 29, arabicName: 'العنكبوت', englishName: 'Al-Ankabut', englishTranslation: 'The Spider', versesCount: 69, revelationType: 'Makki' },
    { number: 30, arabicName: 'الروم', englishName: 'Ar-Rum', englishTranslation: 'The Romans', versesCount: 60, revelationType: 'Makki' },
    { number: 31, arabicName: 'لقمان', englishName: 'Luqman', englishTranslation: 'Luqman', versesCount: 34, revelationType: 'Makki' },
    { number: 32, arabicName: 'السجدة', englishName: 'As-Sajda', englishTranslation: 'The Prostration', versesCount: 30, revelationType: 'Makki' },
    { number: 33, arabicName: 'الأحزاب', englishName: 'Al-Ahzab', englishTranslation: 'The Combined Forces', versesCount: 73, revelationType: 'Madani' },
    { number: 34, arabicName: 'سبأ', englishName: 'Saba', englishTranslation: 'Sheba', versesCount: 54, revelationType: 'Makki' },
    { number: 35, arabicName: 'فاطر', englishName: 'Fatir', englishTranslation: 'Originator', versesCount: 45, revelationType: 'Makki' },
    { number: 36, arabicName: 'يس', englishName: 'Ya-Sin', englishTranslation: 'Ya Sin', versesCount: 83, revelationType: 'Makki' },
    { number: 37, arabicName: 'الصافات', englishName: 'As-Saffat', englishTranslation: 'Those who set the Ranks', versesCount: 182, revelationType: 'Makki' },
    { number: 38, arabicName: 'ص', englishName: 'Sad', englishTranslation: 'Sad', versesCount: 88, revelationType: 'Makki' },
    { number: 39, arabicName: 'الزمر', englishName: 'Az-Zumar', englishTranslation: 'The Troops', versesCount: 75, revelationType: 'Makki' },
    { number: 40, arabicName: 'غافر', englishName: 'Ghafir', englishTranslation: 'The Forgiver', versesCount: 85, revelationType: 'Makki' },
    { number: 41, arabicName: 'فصلت', englishName: 'Fussilat', englishTranslation: 'Explained in Detail', versesCount: 54, revelationType: 'Makki' },
    { number: 42, arabicName: 'الشورى', englishName: 'Ash-Shura', englishTranslation: 'The Consultation', versesCount: 53, revelationType: 'Makki' },
    { number: 43, arabicName: 'الزخرف', englishName: 'Az-Zukhruf', englishTranslation: 'The Ornaments of Gold', versesCount: 89, revelationType: 'Makki' },
    { number: 44, arabicName: 'الدخان', englishName: 'Ad-Dukhan', englishTranslation: 'The Smoke', versesCount: 59, revelationType: 'Makki' },
    { number: 45, arabicName: 'الجاثية', englishName: 'Al-Jathiya', englishTranslation: 'The Crouching', versesCount: 37, revelationType: 'Makki' },
    { number: 46, arabicName: 'الأحقاف', englishName: 'Al-Ahqaf', englishTranslation: 'The Wind-Curved Sandhills', versesCount: 35, revelationType: 'Makki' },
    { number: 47, arabicName: 'محمد', englishName: 'Muhammad', englishTranslation: 'Muhammad', versesCount: 38, revelationType: 'Madani' },
    { number: 48, arabicName: 'الفتح', englishName: 'Al-Fath', englishTranslation: 'The Victory', versesCount: 29, revelationType: 'Madani' },
    { number: 49, arabicName: 'الحجرات', englishName: 'Al-Hujurat', englishTranslation: 'The Rooms', versesCount: 18, revelationType: 'Madani' },
    { number: 50, arabicName: 'ق', englishName: 'Qaf', englishTranslation: 'Qaf', versesCount: 45, revelationType: 'Makki' },
    { number: 51, arabicName: 'الذاريات', englishName: 'Adh-Dhariyat', englishTranslation: 'The Winnowing Winds', versesCount: 60, revelationType: 'Makki' },
    { number: 52, arabicName: 'الطور', englishName: 'At-Tur', englishTranslation: 'The Mount', versesCount: 49, revelationType: 'Makki' },
    { number: 53, arabicName: 'النجم', englishName: 'An-Najm', englishTranslation: 'The Star', versesCount: 62, revelationType: 'Makki' },
    { number: 54, arabicName: 'القمر', englishName: 'Al-Qamar', englishTranslation: 'The Moon', versesCount: 55, revelationType: 'Makki' },
    { number: 55, arabicName: 'الرحمن', englishName: 'Ar-Rahman', englishTranslation: 'The Beneficent', versesCount: 78, revelationType: 'Madani' },
    { number: 56, arabicName: 'الواقعة', englishName: 'Al-Waqi\'a', englishTranslation: 'The Inevitable', versesCount: 96, revelationType: 'Makki' },
    { number: 57, arabicName: 'الحديد', englishName: 'Al-Hadid', englishTranslation: 'The Iron', versesCount: 29, revelationType: 'Madani' },
    { number: 58, arabicName: 'المجادلة', englishName: 'Al-Mujadila', englishTranslation: 'The Pleading Woman', versesCount: 22, revelationType: 'Madani' },
    { number: 59, arabicName: 'الحشر', englishName: 'Al-Hashr', englishTranslation: 'The Exile', versesCount: 24, revelationType: 'Madani' },
    { number: 60, arabicName: 'الممتحنة', englishName: 'Al-Mumtahana', englishTranslation: 'She that is to be examined', versesCount: 13, revelationType: 'Madani' },
    { number: 61, arabicName: 'الصف', englishName: 'As-Saff', englishTranslation: 'The Ranks', versesCount: 14, revelationType: 'Madani' },
    { number: 62, arabicName: 'الجمعة', englishName: 'Al-Jumu\'a', englishTranslation: 'The Congregation, Friday', versesCount: 11, revelationType: 'Madani' },
    { number: 63, arabicName: 'المنافقون', englishName: 'Al-Munafiqun', englishTranslation: 'The Hypocrites', versesCount: 11, revelationType: 'Madani' },
    { number: 64, arabicName: 'التغابن', englishName: 'At-Taghabun', englishTranslation: 'The Mutual Disillusion', versesCount: 18, revelationType: 'Madani' },
    { number: 65, arabicName: 'الطلاق', englishName: 'At-Talaq', englishTranslation: 'The Divorce', versesCount: 12, revelationType: 'Madani' },
    { number: 66, arabicName: 'التحريم', englishName: 'At-Tahrim', englishTranslation: 'The Prohibition', versesCount: 12, revelationType: 'Madani' },
    { number: 67, arabicName: 'الملك', englishName: 'Al-Mulk', englishTranslation: 'The Sovereignty', versesCount: 30, revelationType: 'Makki' },
    { number: 68, arabicName: 'القلم', englishName: 'Al-Qalam', englishTranslation: 'The Pen', versesCount: 52, revelationType: 'Makki' },
    { number: 69, arabicName: 'الحاقة', englishName: 'Al-Haqqa', englishTranslation: 'The Reality', versesCount: 52, revelationType: 'Makki' },
    { number: 70, arabicName: 'المعارج', englishName: 'Al-Ma\'arij', englishTranslation: 'The Ascending Stairways', versesCount: 44, revelationType: 'Makki' },
    { number: 71, arabicName: 'نوح', englishName: 'Nuh', englishTranslation: 'Noah', versesCount: 28, revelationType: 'Makki' },
    { number: 72, arabicName: 'الجن', englishName: 'Al-Jinn', englishTranslation: 'The Jinn', versesCount: 28, revelationType: 'Makki' },
    { number: 73, arabicName: 'المزمل', englishName: 'Al-Muzzammil', englishTranslation: 'The Enshrouded One', versesCount: 20, revelationType: 'Makki' },
    { number: 74, arabicName: 'المدثر', englishName: 'Al-Muddaththir', englishTranslation: 'The Cloaked One', versesCount: 56, revelationType: 'Makki' },
    { number: 75, arabicName: 'القيامة', englishName: 'Al-Qiyama', englishTranslation: 'The Resurrection', versesCount: 40, revelationType: 'Makki' },
    { number: 76, arabicName: 'الإنسان', englishName: 'Al-Insan', englishTranslation: 'The Man', versesCount: 31, revelationType: 'Madani' },
    { number: 77, arabicName: 'المرسلات', englishName: 'Al-Mursalat', englishTranslation: 'The Emissaries', versesCount: 50, revelationType: 'Makki' },
    { number: 78, arabicName: 'النبأ', englishName: 'An-Naba', englishTranslation: 'The Tidings', versesCount: 40, revelationType: 'Makki' },
    { number: 79, arabicName: 'النازعات', englishName: 'An-Nazi\'at', englishTranslation: 'Those who drag forth', versesCount: 46, revelationType: 'Makki' },
    { number: 80, arabicName: 'عبس', englishName: '\'Abasa', englishTranslation: 'He Frowned', versesCount: 42, revelationType: 'Makki' },
    { number: 81, arabicName: 'التكوير', englishName: 'At-Takwir', englishTranslation: 'The Overthrowing', versesCount: 29, revelationType: 'Makki' },
    { number: 82, arabicName: 'الانفطار', englishName: 'Al-Infitar', englishTranslation: 'The Cleaving', versesCount: 19, revelationType: 'Makki' },
    { number: 83, arabicName: 'المطففين', englishName: 'Al-Mutaffifin', englishTranslation: 'The Defrauding', versesCount: 36, revelationType: 'Makki' },
    { number: 84, arabicName: 'الانشقاق', englishName: 'Al-Inshiqaq', englishTranslation: 'The Sundering', versesCount: 25, revelationType: 'Makki' },
    { number: 85, arabicName: 'البروج', englishName: 'Al-Buruj', englishTranslation: 'The Mansions of the Stars', versesCount: 22, revelationType: 'Makki' },
    { number: 86, arabicName: 'الطارق', englishName: 'At-Tariq', englishTranslation: 'The Morning Star', versesCount: 17, revelationType: 'Makki' },
    { number: 87, arabicName: 'الأعلى', englishName: 'Al-A\'la', englishTranslation: 'The Most High', versesCount: 19, revelationType: 'Makki' },
    { number: 88, arabicName: 'الغاشية', englishName: 'Al-Ghashiya', englishTranslation: 'The Overwhelming', versesCount: 26, revelationType: 'Makki' },
    { number: 89, arabicName: 'الفجر', englishName: 'Al-Fajr', englishTranslation: 'The Dawn', versesCount: 30, revelationType: 'Makki' },
    { number: 90, arabicName: 'البلد', englishName: 'Al-Balad', englishTranslation: 'The City', versesCount: 20, revelationType: 'Makki' },
    { number: 91, arabicName: 'الشمس', englishName: 'Ash-Shams', englishTranslation: 'The Sun', versesCount: 15, revelationType: 'Makki' },
    { number: 92, arabicName: 'الليل', englishName: 'Al-Layl', englishTranslation: 'The Night', versesCount: 21, revelationType: 'Makki' },
    { number: 93, arabicName: 'الضحى', englishName: 'Ad-Dhuha', englishTranslation: 'The Morning Hours', versesCount: 11, revelationType: 'Makki' },
    { number: 94, arabicName: 'الشرح', englishName: 'Ash-Sharh', englishTranslation: 'The Relief', versesCount: 8, revelationType: 'Makki' },
    { number: 95, arabicName: 'التين', englishName: 'At-Tin', englishTranslation: 'The Fig', versesCount: 8, revelationType: 'Makki' },
    { number: 96, arabicName: 'العلق', englishName: 'Al-\'Alaq', englishTranslation: 'The Clot', versesCount: 19, revelationType: 'Makki' },
    { number: 97, arabicName: 'القدر', englishName: 'Al-Qadr', englishTranslation: 'The Power', versesCount: 5, revelationType: 'Makki' },
    { number: 98, arabicName: 'البينة', englishName: 'Al-Bayyina', englishTranslation: 'The Clear Proof', versesCount: 8, revelationType: 'Madani' },
    { number: 99, arabicName: 'الزلزلة', englishName: 'Az-Zalzala', englishTranslation: 'The Earthquake', versesCount: 8, revelationType: 'Madani' },
    { number: 100, arabicName: 'العاديات', englishName: 'Al-\'Adiyat', englishTranslation: 'The Courser', versesCount: 11, revelationType: 'Makki' },
    { number: 101, arabicName: 'القارعة', englishName: 'Al-Qari\'a', englishTranslation: 'The Calamity', versesCount: 11, revelationType: 'Makki' },
    { number: 102, arabicName: 'التكاثر', englishName: 'At-Takathur', englishTranslation: 'The Rivalry in world increase', versesCount: 8, revelationType: 'Makki' },
    { number: 103, arabicName: 'العصر', englishName: 'Al-\'Asr', englishTranslation: 'The Declining Day', versesCount: 3, revelationType: 'Makki' },
    { number: 104, arabicName: 'الهمزة', englishName: 'Al-Humaza', englishTranslation: 'The Traducer', versesCount: 9, revelationType: 'Makki' },
    { number: 105, arabicName: 'الفيل', englishName: 'Al-Fil', englishTranslation: 'The Elephant', versesCount: 5, revelationType: 'Makki' },
    { number: 106, arabicName: 'قريش', englishName: 'Quraysh', englishTranslation: 'Quraysh', versesCount: 4, revelationType: 'Makki' },
    { number: 107, arabicName: 'الماعون', englishName: 'Al-Ma\'un', englishTranslation: 'The Small Kindnesses', versesCount: 7, revelationType: 'Makki' },
    { number: 108, arabicName: 'الكوثر', englishName: 'Al-Kawthar', englishTranslation: 'The Abundance', versesCount: 3, revelationType: 'Makki' },
    { number: 109, arabicName: 'الكافرون', englishName: 'Al-Kafirun', englishTranslation: 'The Disbelievers', versesCount: 6, revelationType: 'Makki' },
    { number: 110, arabicName: 'النصر', englishName: 'An-Nasr', englishTranslation: 'The Divine Support', versesCount: 3, revelationType: 'Madani' },
    { number: 111, arabicName: 'المسد', englishName: 'Al-Masad', englishTranslation: 'The Palm Fiber', versesCount: 5, revelationType: 'Makki' },
    { number: 112, arabicName: 'الإخلاص', englishName: 'Al-Ikhlas', englishTranslation: 'The Sincerity', versesCount: 4, revelationType: 'Makki' },
    { number: 113, arabicName: 'الفلق', englishName: 'Al-Falaq', englishTranslation: 'The Daybreak', versesCount: 5, revelationType: 'Makki' },
    { number: 114, arabicName: 'الناس', englishName: 'An-Nas', englishTranslation: 'The Mankind', versesCount: 6, revelationType: 'Makki' },
];

export const getSurahInfo = (surahNumber: number): SurahInfo | undefined => {
    return surahList.find(s => s.number === surahNumber);
};
